apiVersion: v1
kind: Secret
metadata:
  name: {{.Name}}-integrations-letsencrypt-certificate
  namespace: {{.Namespace}}
  labels:
    {{- range $key, $value := .Labels}}
    {{$key}}: {{$value}}
    {{- end}}
  annotations:
    ziplinee.io/letsencrypt-certificate: "true"
    ziplinee.io/letsencrypt-certificate-hostnames: "{{.ManifestData.IntegrationsHostname}},{{.ManifestData.IntegrationsHostname2}}"
type: Opaque