apiVersion: v1
kind: Secret
metadata:
  name: {{.Name}}-gcp-service-account-gke
  namespace: {{.Namespace}}
  labels:
    {{- range $key, $value := .Labels}}
    {{$key}}: {{$value}}
    {{- end}}
    type: gcp-service-account
  annotations:
    estafette.io/gcp-service-account: 'true'
    estafette.io/gcp-service-account-name: 'estafette-credentials-gke'
    {{- if .DisableServiceAccountKeyRotation}}
    estafette.io/gcp-service-account-disable-key-rotation: 'true'
    {{- end}}
type: Opaque