apiVersion: v1
kind: Secret
metadata:
  name: {{.Name}}-gcp-service-account-gke
  namespace: {{.Namespace}}
  labels:
    {{- range $key, $value := .Labels}}
    {{$key}}: {{$value}}
    {{- end}}
    type: gcp-service-account
  annotations:
    ziplinee.io/gcp-service-account: 'true'
    ziplinee.io/gcp-service-account-name: 'ziplinee-credentials-gke'
    {{- if .DisableServiceAccountKeyRotation}}
    ziplinee.io/gcp-service-account-disable-key-rotation: 'true'
    {{- end}}
type: Opaque