clearDefaultTrustedImages: true
trustedImages:
- path: extensionci/docker
  runDocker: true
  injectedCredentialTypes:
  - container-registry
- path: extensionci/gke
  injectedCredentialTypes:
  - kubernetes-engine
- path: extensionci/bitbucket-status
  injectedCredentialTypes:
  - bitbucket-api-token
- path: extensionci/github-status
  injectedCredentialTypes:
  - github-api-token
- path: extensionci/slack-build-status
  injectedCredentialTypes:
  - slack-webhook
- path: extensionci/dotnet
  injectedCredentialTypes:
  - nuget-server
  - sonarqube-server
- path: docker
  runDocker: true
- path: multiple-git-sources-test
  injectedCredentialTypes:
  - bitbucket-api-token
  - github-api-token
  - cloudsource-api-token